import { defineConfig } from "vite";
import path from "path";

// Vite plugins
import react from "@vitejs/plugin-react";
import compileTime from "vite-plugin-compile-time";
import { ViteEjsPlugin as ejs } from "vite-plugin-ejs";
import minifyHtml from "vite-plugin-html-minifier-terser";
import svgo from "./vite/svgo";
import publicPath from "vite-plugin-public-path";
import { viteExternalsPlugin as externals } from "vite-plugin-externals";
import { visualizer } from "rollup-plugin-visualizer";
import { replacePlugin } from "rolldown/plugins";

// Node polyfill
import { NodeModulesPolyfillPlugin } from "@esbuild-plugins/node-modules-polyfill";
import nodePolyfills from "@rolldown/plugin-node-polyfills";

// Others
import getGitCommitInfo from "git-commit-info";
import { Options as HtmlMinifierOptions } from "html-minifier-terser";

import tsconfig from "./tsconfig.json";

const isDev = process.env.NODE_ENV !== "production";

const tsconfigPathAliases = Object.fromEntries(
  Object.entries(tsconfig.compilerOptions.paths).map(([key, values]) => {
    let value = values[0];
    if (key.endsWith("/*")) {
      key = key.slice(0, -2);
      value = value.slice(0, -2);
    }

    const nodeModulesPrefix = "node_modules/";
    if (value.startsWith(nodeModulesPrefix)) {
      value = value.replace(nodeModulesPrefix, "");
    } else {
      value = path.join(__dirname, value);
    }

    return [key, value];
  })
);

const semanticUiCssComponents = [
  "accordion",
  "breadcrumb",
  "button",
  "checkbox",
  "comment",
  "container",
  "dimmer",
  "divider",
  "dropdown",
  "flag",
  "form",
  "grid",
  "header",
  "icon",
  "image",
  "input",
  "item",
  "label",
  "list",
  "loader",
  "menu",
  "message",
  "modal",
  "placeholder",
  "popup",
  "progress",
  "reset",
  "search",
  "segment",
  "sidebar",
  "statistic",
  "table",
  "tab",
  "text",
  "transition"
];

// These packages are simply loaded in HTML with the JS path
const baseExternalPackages: Record<
  string,
  {
    cdnjsName?: string;
    globalVariableName?: string;
    devScript?: string | string[];
    prodScript?: string | string[];
    css?: string | string[];
  }
> = {
  react: {
    globalVariableName: "React",
    devScript: "umd/react.development.js",
    prodScript: "umd/react.production.min.js"
  },
  "react-dom": {
    globalVariableName: "ReactDOM",
    devScript: "umd/react-dom.development.js",
    prodScript: "umd/react-dom.production.min.js"
  },
  mobx: { globalVariableName: "mobx", devScript: "mobx.umd.development.js", prodScript: "mobx.umd.production.min.js" },
  noty: { globalVariableName: "Noty", devScript: "noty.min.js", css: "noty.min.css" },
  "semantic-ui-react": { globalVariableName: "semanticUIReact", devScript: "semantic-ui-react.min.js" },
  "fomantic-ui-css": {
    cdnjsName: "fomantic-ui",
    css: semanticUiCssComponents.map(component => `components/${component}.min.css`)
  }
};

const externalPackageVersions = Object.fromEntries(
  [
    // These packages are loaded separatedly in JS code when needed
    "monaco-editor",
    "@mathjax/src",
    "@twemoji/api",
    "prismjs",

    ...Object.keys(baseExternalPackages)
  ].map(packageName => [
    baseExternalPackages[packageName]?.cdnjsName || packageName,
    require(`${packageName}/package.json`).version
  ])
);

export default defineConfig({
  server: {
    port: 3000
  },
  plugins: [
    compileTime(),
    ejs({
      gitCommitInfo: getGitCommitInfo(),
      externalPackages: Object.entries(baseExternalPackages).map(
        ([packageName, { cdnjsName, devScript, prodScript, css }]) => [
          cdnjsName || packageName,
          !isDev && prodScript ? prodScript : devScript,
          css
        ]
      ),
      externalPackageVersions
    }),
    svgo({
      plugins: [
        "preset-default",
        {
          name: "sortAttrs",
          params: {
            xmlnsOrder: "alphabetical"
          } as any
        }
      ]
    }),
    publicPath({
      publicPathExpression: "window.publicPath",
      html: {
        functionNameAddLinkTag: "addLinkTag",
        addLinkTagsPlaceholder: "// __add_link_tags__",
        functionNameAddScriptTag: "addScriptTag",
        addScriptTagsPlaceholder: "// __add_script_tags__"
      }
    }),
    minifyHtml(<HtmlMinifierOptions>{
      includeAutoGeneratedTags: true,
      removeAttributeQuotes: false,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      sortClassName: true,
      useShortDoctype: false,
      collapseWhitespace: true,
      removeComments: true,
      ignoreCustomComments: [/Menci/],
      minifyJS: {
        parse: {
          ecma: 8
        },
        compress: {
          ecma: 5,
          warnings: false,
          comparisons: false,
          inline: 2
        },
        mangle: {
          safari10: true
        },
        output: {
          ecma: 5,
          comments: false
        }
      },
      minifyCSS: true
    }),
    externals({
      "monaco-editor": "Monaco",
      ...Object.fromEntries(
        Object.entries(baseExternalPackages)
          .filter(([, { globalVariableName }]) => globalVariableName)
          .map(([packageName, { globalVariableName }]) => [packageName, globalVariableName])
      )
    }),
    visualizer()
  ],
  base: isDev ? "/" : "/__vite_base__/",
  experimental: {
    renderBuiltUrl(filename, { type, hostId, hostType }) {
      if (hostType === 'js') {
        return { runtime: `window.publicPath + "${filename}"` }
      }
    }
  },
  resolve: {
    alias: {
      ...tsconfigPathAliases
    }
  },
  build: {
    minify: "terser",
    sourcemap: true,
    target: "esnext",
    rolldownOptions: {
      output: {
        sourcemapDebugIds: true,
      },
      transform: {
        inject: {
          process: 'process',
        }
      },
      plugins: [
        nodePolyfills({
          ignore(importee, importer) {
            return importee !== 'path';
          }
        }),
        replacePlugin(
          { 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production') },
          {
            objectGuards: true,
            preventAssignment: true,
            sourcemap: true,
          }
        )
      ]
    }
  },
  define: {
    EXTERNAL_PACKAGE_VERSION: JSON.stringify(externalPackageVersions)
  },
  optimizeDeps: {
    exclude: ["mobx-utils/mobx-utils.module.js"],
    rolldownOptions: {
      plugins: [
        // Enable esbuild polyfill plugins
        NodeModulesPolyfillPlugin()
      ]
    }
  }
});
